alias: 'TelegramBot /driveway_camera'
trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/driveway_camera'
action:
  - service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.user_id }}'
      message:  "Driveway pic coming right up, {{ trigger.event.data.from_first }}!"
      keyboard:
        - '/weather'
        - '/front_door_camera'
        - '/driveway_camera'
  - service: telegram_bot.send_photo
    data_template:
      url: !secret driveway_authed_url
      target: '{{ trigger.event.data.user_id }}'
      keyboard:
        - '/weather'
        - '/front_door_camera'
        - '/driveway_camera'
