- platform: time_date
  display_options:
      - 'time'
      - 'date'
      - 'date_time'
- platform: template
  sensors:
    vacuum_status:
      friendly_name: "Vacuum - Status"
      value_template: "Status: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}"
    vacuum_battery:
      friendly_name: "Vacuum - Battery"
      value_template: "{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_level }}"
      device_class: battery
      unit_of_measurement: '%'
- platform: mqtt
  state_topic: 'monitor/front_house/64:a2:f9:45:f8:d8'
  value_template: '{{ value_json.confidence }}'
  availability_topic: 'monitor/front_house/status'
  unit_of_measurement: '%'
  name: "BT Sensor Front for Curtis' OnePlus 6"
  json_attributes:
    - timestamp
    - name
    - manufacturer
    - rssi
- platform: template
  sensors:
    curtis_bayesian:
      friendly_name: Curtis (Bayesian Sensor)
      value_template: >
                    {% if is_state('binary_sensor.curtis_presence_bayesian', 'on') %}
                    home
                    {% else %}
                    not_home
                    {% endif %}

# - platform: mqtt
#   state_topic: 'monitor/middle_house/64:a2:f9:45:f8:d8'
#   availability_topic: 'monitor/middle_house/status'
#   value_template: '{{ value_json.confidence }}'
#   unit_of_measurement: '%'
#   name: "BT Sensor Middle for Curtis' OnePlus 6"
