- platform: flux
  name: 'Light Temperature Control'
  lights:
    - light.curtis_bedroom
    - light.kitchen
    - light.dining_room
    - light.lounge_room
    - light.garage
  disable_brightness_adjust: true
  start_colortemp: 5000
  sunset_colortemp: 3500
  stop_colortemp: 2500
  mode: mired
