- alias: "Turn on dining room light after motion at night"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_dining_room
      to: 'on'
  condition:
    - condition: time
      after: '21:45:00'
      before: '06:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.xiaomi_gateway
        brightness: 255

- alias: "Turn off dining room light after no motion"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_dining_room
      to: 'off'
      for:
        minutes: 1
  action:
    - service: light.turn_off
      data:
        entity_id: light.xiaomi_gateway
        transition: 5
