alias: "Vacuum scheduled cleanup"
trigger:
  platform: time
  at: '13:15:00'
condition:
  condition: time
  weekday:
    - mon
    - wed
    - fri
action:
  - service: vacuum.turn_on
    data:
      entity_id: vacuum.xiaomi_vacuum_cleaner
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.xiaomi_vacuum_cleaner
      fan_speed: "Turbo"
