- alias: "Doorbell"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_doorbell
  action:
    service: script.turn_on
    entity_id: script.doorbell_script
